"""
Generated Animation Script
==========================
Auto-generated by ScriptDirector.
"""

from domain.modules.script_director.timeline_planner_module import Action, ActionType, Timeline
from domain.value_objects.vector import Vector2


def load_script() -> Timeline:
    """Factory function to return the planned timeline."""
    timeline = Timeline()

    # Action 0: NONE on root_0
    action_0 = Action(
        layer_id="root_0",
        action_type=ActionType.NONE,
        start_time=0.0,
        duration=0.0,
        target_position=Vector2(540.0, 540.0),
        easing=None,
    )
    timeline.add_action(action_0)

    # Action 1: BRUSH on root_1
    action_1 = Action(
        layer_id="root_1",
        action_type=ActionType.BRUSH,
        start_time=2.0,
        duration=3.0,
        target_position=Vector2(244.5, 577.0),
        easing=None,
    )
    timeline.add_action(action_1)

    # Action 2: BRUSH on root_2
    action_2 = Action(
        layer_id="root_2",
        action_type=ActionType.BRUSH,
        start_time=6.5,
        duration=3.0,
        target_position=Vector2(829.0, 591.0),
        easing=None,
    )
    timeline.add_action(action_2)

    # Action 3: BRUSH on root_3
    action_3 = Action(
        layer_id="root_3",
        action_type=ActionType.BRUSH,
        start_time=11.0,
        duration=3.0,
        target_position=Vector2(531.5, 309.5),
        easing=None,
    )
    timeline.add_action(action_3)

    return timeline
