"""
Script Generator Module
=======================

Generates executable Python scripts from Timeline objects.
This allows the animation plan to be saved, versioned, and executed by other modules.
"""

from ....entities.timeline_entity import TimelineEntity


def generate_python_script(timeline: TimelineEntity, output_path: str = None) -> str:
    """
    Generate a Python script string from a Timeline object.

    Args:
        timeline: The source Timeline to serialize.
        output_path: Optional path to save the file to.

    Returns:
        The generated Python code as a string.
    """
    lines = []

    # 1. Header & Imports
    lines.append('"""')
    lines.append("Generated Animation Script")
    lines.append("==========================")
    lines.append("Auto-generated by ScriptDirector.")
    lines.append('"""')
    lines.append("# Imports updated for Hexagonal Architecture")
    lines.append("from domain.entities.timeline_entity import TimelineEntity")
    lines.append("from domain.entities.action_entity import Action")
    lines.append("from domain.value_objects.animation.action_type_value import ActionType")
    lines.append("from domain.value_objects.geometry.vector_value import Vector2")
    lines.append(
        "from domain.value_objects.animation.easing_curve_value import EasingCurve, EasingType"
    )
    lines.append("")
    lines.append("def load_script() -> TimelineEntity:")
    lines.append('    """Factory function to return the planned timeline."""')
    lines.append("    timeline = TimelineEntity()")
    lines.append("")

    # 2. Serialize Actions
    for idx, action in enumerate(timeline.actions):
        lines.append(f"    # Action {idx}: {action.action_type.name} on {action.layer_id}")

        # Serialize Easing
        easing_str = "None"
        if action.easing:
            # Reconstruct EasingCurve object code
            # Assuming we use presets mostly, but for robust serialization:
            easing_type_str = f"EasingType.{action.easing.easing_type.name}"
            easing_str = f"EasingCurve({easing_type_str}, overshoot={action.easing.overshoot})"

        # Serialize Target Position
        target_pos_str = "None"
        if action.target_position:
            target_pos_str = f"Vector2({action.target_position.x}, {action.target_position.y})"

        lines.append(f"    action_{idx} = Action(")
        lines.append(f'        layer_id="{action.layer_id}",')
        lines.append(f"        action_type=ActionType.{action.action_type.name},")
        lines.append(f"        start_time={action.start_time},")
        lines.append(f"        duration={action.duration},")
        lines.append(f"        target_position={target_pos_str},")
        lines.append(f"        easing={easing_str}")
        lines.append("    )")
        lines.append(f"    timeline.add_action(action_{idx})")
        lines.append("")

    # 3. Footer
    lines.append("    return timeline")
    lines.append("")

    script_content = "\n".join(lines)

    # 4. Save to file if requested
    if output_path:
        with open(output_path, "w") as f:
            f.write(script_content)

    return script_content
